services:
  app:
    image: ghcr.io/guimox/f1-fia-doc/f1fia:v1.0.0
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - OPENAI_TOKEN=${OPENAI_TOKEN}
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      - SPRING_PROFILES_ACTIVE=prd
      - POSTGRES_DB=your_db_name
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
