services:
  app:
    image: ghcr.io/guimox/f1-fia-doc/f1fia:v1.0.0
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/f1fia_db
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - OPENAI_TOKEN=${OPENAI_TOKEN}
      - SPRING_PROFILES_ACTIVE=prd
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15
    platform: linux/amd64
    environment:
      - POSTGRES_DB=f1fia_db
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: