name: Build and Deploy F1 FIA Doc

on:
  push:
    branches:
      - testing-cicd

jobs:
  build-deploy:
    name: Build and Deploy F1 FIA Doc
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: 17

      - name: Build the App
        run: mvn clean package -Pprd -DskipTests --file pom.xml

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Push Multi-Architecture Docker Image to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/${{ github.repository }}/${{ secrets.DOCKER_CONTAINER_NAME }}:v1.0.0
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create app directory on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_IP_ADDRESS }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            if [ ! -d "/home/${{ secrets.VPS_USERNAME }}/apps/f1-fia-doc" ]; then
              mkdir -p /home/${{ secrets.VPS_USERNAME }}/apps/f1-fia-doc
            fi

      - name: Upload docker-compose-prd.yml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP_ADDRESS }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: "docker-compose-prd.yml"
          target: "/home/${{ secrets.VPS_USERNAME }}/apps/f1-fia-doc/"

      - name: Create .env file on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_IP_ADDRESS }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            cd /home/${{ secrets.VPS_USERNAME }}/apps/f1-fia-doc
            cat > .env << EOF
            SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}
            SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}
            OPENAI_TOKEN=${{ secrets.OPENAI_TOKEN }}
            EOF
            chmod 600 .env

      - name: Upload db initialization files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP_ADDRESS }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          source: "db/*"
          target: "/home/${{ secrets.VPS_USERNAME }}/apps/f1-fia-doc/"

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_IP_ADDRESS }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            echo "${{ secrets.PAT_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

            cd /home/${{ secrets.VPS_USERNAME }}/apps/f1-fia-doc

            docker pull ghcr.io/${{ github.repository }}/${{ secrets.DOCKER_CONTAINER_NAME }}:v1.0.0

            docker compose -f docker-compose-prd.yml down

            docker compose -f docker-compose-prd.yml up -d --remove-orphans

            docker image prune -f